# unbind
unbind C-h
unbind C-j
unbind C-k
unbind C-l

# ペインの開始番号を 0 から 1 に変更する
set-option -g base-index 1

# マウスでウィンドウ・ペインの切り替えやリサイズを可能にする
set-option -g mouse on                    # tmux 2.1以降

# マウスホイールでヒストリではなくスクロールできるようにする
set -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# ステータスバーの背景色を変更する
set-option -g status-bg "colour255"

# 画面の色
set-option default-terminal "screen-256color"

# -rオプションでバインドしたキーは一定時間連続入力可能
# デフォルトは500ms
set repeat-time 500

# Escの反応速度
set -sg escape-time 0

# ペインのサイズの変更
bind -r S-left resize-pane -L 3
bind -r S-down resize-pane -D 3
bind -r S-up resize-pane -U 3
bind -r S-right resize-pane -R 3
# ペインの最大化
bind -n C-z resize-pane -Z
# ペインの分割
bind | split-window -h
bind - split-window -v
# ペインのフォーカス
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -n S-left select-pane -L
bind -n S-down select-pane -D
bind -n S-up select-pane -U
bind -n S-right select-pane -R

# ウィンドウのフォーカス
bind -r n next-window
bind -r p previous-window
bind -r C-n next-window
bind -r C-p previous-window


# window-statusの見た目を変更
setw -g window-status-current-format '#[bg=colour2,fg=colour255] #I #W '
setw -g window-status-format '#[fg=colour242] #I #W '

# prefixが押された時に背景色が変わる
setw -g window-status-current-format '#[bg=colour2,fg=colour255]#{?client_prefix,#[bg=colour3],} #I #W '

#参考url
# https://qiita.com/youichiro/items/dd54c38c2f3873348c78

# コピーモードをviモードに変更
set-window-option -g mode-keys vi
# 選択開始キーをvに変更
bind -T copy-mode-vi v send-keys -X begin-selection
# クリップボードへのコピー
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
# 矩形選択の切り替え設定
# ※あくまで選択の切り替えなので、選択開始はvを押してから
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
# Vで行ごとの選択
bind -T copy-mode-vi V send-keys -X select-line
# Escで選択範囲の解除
bind -T copy-mode-vi C-[ send-keys -X clear-selection


# Prefix(Ctrl-b)をCtrl-gに変更する
unbind-key C-b
set-option -g prefix C-g
bind-key C-g send-prefix
