#!/bin/zsh
# -----------------------------------------------------------
# prezto初期設定
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
#------------------------------------------------------------
# --------------------------------------------------
# path
# --------------------------------------------------
path=(
  /opt/homebrew/bin
  $HOME/.cargo/bin
  $HOME/mycommands
  $HOME/bin
  /usr/local/bin
  $HOME/.deno/bin
  $HOME/.nodebrew/current/bin
  $path
)

hash -r

# --------------------------------------------------
# prompt
# --------------------------------------------------
if [[ -f "$HOME/dotfiles/zsh/prompt.zsh" ]]; then
  source "$HOME/dotfiles/zsh/prompt.zsh"
fi

# --------------------------------------------------
# options
# --------------------------------------------------
if [[ -f "$HOME/dotfiles/zsh/options.zsh" ]]; then
  source "$HOME/dotfiles/zsh/options.zsh"
fi

# --------------------------------------------------
# bindkey
# --------------------------------------------------
if [[ -f "$HOME/dotfiles/zsh/bindkey.zsh" ]]; then
  source "$HOME/dotfiles/zsh/bindkey.zsh"
fi

# --------------------------------------------------
# alias
# --------------------------------------------------
if [[ -f "$HOME/dotfiles/zsh/alias.zsh" ]]; then
  source "$HOME/dotfiles/zsh/alias.zsh"
fi

# --------------------------------------------------
# functions
# --------------------------------------------------
if [[ -f "$HOME/dotfiles/zsh/func.zsh" ]]; then
  source "$HOME/dotfiles/zsh/func.zsh"
fi

#-------------------------------------------------
# 環境変数
#-------------------------------------------------
if [[ -f "$HOME/dotfiles/zsh/env.zsh" ]]; then
  source "$HOME/dotfiles/zsh/env.zsh"
fi

#-------------------------------------------------
# fzf set up
#-------------------------------------------------
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# fzf-extra
# https://github.com/atweiden/fzf-extras
[[ -e "$HOME/.fzf-extras/fzf-extras.zsh" ]] \
  && source "$HOME/.fzf-extras/fzf-extras.zsh"

#-------------------------------------------------
# direnv set up
#-------------------------------------------------
command -v direnv >/dev/null && eval "$(direnv hook zsh)"

#-------------------------------------------------
# direnv set up
#-------------------------------------------------
[ -f "$HOME/.secrets/openai.sh" ] && source "$HOME/.secrets/openai.sh"

#-------------------------------------------------
# Iterm使用時のみ
#-------------------------------------------------
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

#-------------------------------------------------
# tmux auto attach (iTerm only)
#-------------------------------------------------
if [[ -o interactive ]] \
  && [[ -z "$TMUX" ]] \
  && [[ -n "$ITERM_SESSION_ID" ]] \
  && command -v tmux >/dev/null; then
  if type tmux_start >/dev/null 2>&1; then
    tmux_start
  fi
fi
