local define = {
  e    = { expr    = true },
  b    = { buffer  = true },
  n    = { noremap = true },
  s    = { silent  = true },
  eb   = { expr    = true, buffer  = true, },
  en   = { expr    = true,                 noremap = true, },
  es   = { expr    = true,                                 silent = true, },
  ebn  = { expr    = true, buffer = true,  noremap = true, },
  ebs  = { expr    = true, buffer = true,                  silent = true, },
  ens  = { expr    = true,                 noremap = true, silent = true, },
  ebns = { expr    = true, buffer = true,  noremap = true, silent = true, },
  bn   = {                 buffer  = true, noremap = true, },
  bns  = {                 buffer  = true, noremap = true, silent = true, },
  ns   = {                                 noremap = true, silent = true, },
  ew    = { expr    = true,                                                   nowait = true },
  bw    = { buffer  = true,                                                   nowait = true },
  nw    = { noremap = true,                                                   nowait = true },
  sw    = { silent  = true,                                                   nowait = true },
  ebw   = { expr    = true, buffer  = true,                                   nowait = true },
  enw   = { expr    = true,                 noremap = true,                   nowait = true },
  esw   = { expr    = true,                                 silent = true,    nowait = true },
  ebnw  = { expr    = true, buffer = true,  noremap = true,                   nowait = true },
  ebsw  = { expr    = true, buffer = true,                  silent = true,    nowait = true },
  ensw  = { expr    = true,                 noremap = true, silent = true,    nowait = true },
  ebnsw = { expr    = true, buffer = true,  noremap = true, silent = true,    nowait = true },
  bnw   = {                 buffer  = true, noremap = true,                   nowait = true },
  bnsw  = {                 buffer  = true, noremap = true, silent = true,    nowait = true },
  nsw   = {                                 noremap = true, silent = true,    nowait = true },
}

return define
