model = "gpt-5.5"
personality = "pragmatic"
model_reasoning_effort = "medium"
notify = ["python3", "/Users/tokumasa/dotfiles/codex/scripts/notify.py"]

[projects."/Users/tokumasa/github/qmk/keyball"]
trust_level = "trusted"

[projects."/Users/tokumasa/test/perceptron"]
trust_level = "trusted"

[projects."/Users/tokumasa/dotfiles"]
trust_level = "trusted"

[projects."/Users/tokumasa"]
trust_level = "trusted"

[projects."/Users/tokumasa/Projects/KSider"]
trust_level = "trusted"

[projects."/Users/tokumasa/temp/MNIST"]
trust_level = "trusted"

[projects."/Users/tokumasa/Projects/KneeSider"]
trust_level = "trusted"

[projects."/Users/tokumasa/Nextcloud/office_works/発表データ/2026新人発表用/dicom"]
trust_level = "trusted"

[projects."/Users/tokumasa/.ssh"]
trust_level = "trusted"

[projects."/Users/tokumasa/github/BBManager"]
trust_level = "trusted"

[projects."/Users/tokumasa/github/PittoLog"]
trust_level = "trusted"

[projects."/Users/tokumasa/Projects/WanaLyzer3.0"]
trust_level = "trusted"

[projects."/Users/tokumasa/Projects/WanaLyser"]
trust_level = "trusted"

[projects."/Users/tokumasa/github/FiRec"]
trust_level = "trusted"

[projects."/Users/tokumasa/github/WanaLyser"]
trust_level = "trusted"

[notice]
hide_gpt5_1_migration_prompt = true

[notice.model_migrations]
"gpt-5.1-codex" = "gpt-5.2-codex"
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"

[plugins."github@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser-use@openai-bundled"]
enabled = true

[marketplaces.openai-bundled]
last_updated = "2026-05-07T00:26:32Z"
source_type = "local"
source = "/Users/tokumasa/dotfiles/codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-01T02:24:26Z"
source_type = "local"
source = "/Users/tokumasa/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[tui]
status_line = ["model-with-reasoning", "current-dir", "five-hour-limit", "weekly-limit", "used-tokens", "task-progress"]

[tui.keymap.composer]
submit = "f6"

[tui.model_availability_nux]
"gpt-5.5" = 4
